apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s